name: 'Actions SSM'
description: 'load AWS SSM Parameters into environment variables'
author: 'Khue'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  ssm-path:
    description: 'AWS SSM path for parameter (eg. `/ssm/parameter`)'
    required: true
  out:
    description: 'outfile'
    required: false
  get-children:
    description: 'Define to get parameters by path, retrieving all children values'
    required: false
  prefix:
    description: 'Set a prefix on the environment variable'
    required: false
  decryption:
    description: 'Whether the parameter must be decrypted or not'
    required: false
  mask-values:
    description: 'Indicates if extracted values should be masked in GitHub action logs'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
